# A Massive Universe of diverse NSE/BSE stocks mapped by their symbol to their Sector/Name.
# This prevents sequentially fetching individual Ticker info which causes severe rate-limiting.

NSE_UNIVERSE = {
    # NIFTY 50 Core
    "RELIANCE.NS": {"name": "Reliance Industries", "sector": "Energy", "market_cap": "Mega Cap"},
    "TCS.NS": {"name": "Tata Consultancy Services", "sector": "IT", "market_cap": "Mega Cap"},
    "HDFCBANK.NS": {"name": "HDFC Bank", "sector": "Banking", "market_cap": "Mega Cap"},
    "ICICIBANK.NS": {"name": "ICICI Bank", "sector": "Banking", "market_cap": "Mega Cap"},
    "BHARTIARTL.NS": {"name": "Bharti Airtel", "sector": "Telecom", "market_cap": "Mega Cap"},
    "SBIN.NS": {"name": "State Bank of India", "sector": "Banking", "market_cap": "Mega Cap"},
    "INFY.NS": {"name": "Infosys", "sector": "IT", "market_cap": "Large Cap"},
    "L&T.NS": {"name": "Larsen & Toubro", "sector": "Infrastructure", "market_cap": "Large Cap"},
    "ITC.NS": {"name": "ITC Limited", "sector": "FMCG", "market_cap": "Large Cap"},
    "HINDUNILVR.NS": {"name": "Hindustan Unilever", "sector": "FMCG", "market_cap": "Large Cap"},
    "AXISBANK.NS": {"name": "Axis Bank", "sector": "Banking", "market_cap": "Large Cap"},
    "KOTAKBANK.NS": {"name": "Kotak Mahindra Bank", "sector": "Banking", "market_cap": "Large Cap"},
    "BAJFINANCE.NS": {"name": "Bajaj Finance", "sector": "Finance", "market_cap": "Large Cap"},
    "MARUTI.NS": {"name": "Maruti Suzuki", "sector": "Auto", "market_cap": "Large Cap"},
    "HCLTECH.NS": {"name": "HCL Technologies", "sector": "IT", "market_cap": "Large Cap"},
    "ASIANPAINT.NS": {"name": "Asian Paints", "sector": "Consumer", "market_cap": "Large Cap"},
    "TATAMOTORS.NS": {"name": "Tata Motors", "sector": "Auto", "market_cap": "Large Cap"},
    "M&M.NS": {"name": "Mahindra & Mahindra", "sector": "Auto", "market_cap": "Large Cap"},
    "SUNPHARMA.NS": {"name": "Sun Pharmaceutical", "sector": "Pharma", "market_cap": "Large Cap"},
    "NTPC.NS": {"name": "NTPC Limited", "sector": "Energy", "market_cap": "Large Cap"},
    "ULTRACEMCO.NS": {"name": "UltraTech Cement", "sector": "Infrastructure", "market_cap": "Large Cap"},
    "TITAN.NS": {"name": "Titan Company", "sector": "Consumer", "market_cap": "Large Cap"},
    "TATASTEEL.NS": {"name": "Tata Steel", "sector": "Metals", "market_cap": "Large Cap"},
    "POWERGRID.NS": {"name": "Power Grid Corp", "sector": "Energy", "market_cap": "Large Cap"},
    "BAJAJFINSV.NS": {"name": "Bajaj Finserv", "sector": "Finance", "market_cap": "Large Cap"},
    
    # Next 100 Highly Liquid (NIFTY Next 50 + Midcaps)
    "ADANIENT.NS": {"name": "Adani Enterprises", "sector": "Infrastructure", "market_cap": "Large Cap"},
    "ADANIPORTS.NS": {"name": "Adani Ports", "sector": "Infrastructure", "market_cap": "Large Cap"},
    "COALINDIA.NS": {"name": "Coal India", "sector": "Metals", "market_cap": "Large Cap"},
    "ONGC.NS": {"name": "Oil & Natural Gas Corp", "sector": "Energy", "market_cap": "Large Cap"},
    "WIPRO.NS": {"name": "Wipro", "sector": "IT", "market_cap": "Large Cap"},
    "ADANIENSOL.NS": {"name": "Adani Energy Solutions", "sector": "Energy", "market_cap": "Large Cap"},
    "ADANIGREEN.NS": {"name": "Adani Green Energy", "sector": "Energy", "market_cap": "Large Cap"},
    "ZOMATO.NS": {"name": "Zomato", "sector": "Consumer", "market_cap": "Large Cap"},
    "IRFC.NS": {"name": "Indian Railway Finance", "sector": "Finance", "market_cap": "Large Cap"},
    "JIOFIN.NS": {"name": "Jio Financial Services", "sector": "Finance", "market_cap": "Large Cap"},
    "HAL.NS": {"name": "Hindustan Aeronautics", "sector": "Defense", "market_cap": "Large Cap"},
    "PNB.NS": {"name": "Punjab National Bank", "sector": "Banking", "market_cap": "Mid Cap"},
    "BANKBARODA.NS": {"name": "Bank of Baroda", "sector": "Banking", "market_cap": "Mid Cap"},
    "VEDL.NS": {"name": "Vedanta Limited", "sector": "Metals", "market_cap": "Large Cap"},
    "JSWSTEEL.NS": {"name": "JSW Steel", "sector": "Metals", "market_cap": "Large Cap"},
    "TECHM.NS": {"name": "Tech Mahindra", "sector": "IT", "market_cap": "Large Cap"},
    "HINDALCO.NS": {"name": "Hindalco Industries", "sector": "Metals", "market_cap": "Large Cap"},
    "GRASIM.NS": {"name": "Grasim Industries", "sector": "Metals", "market_cap": "Large Cap"},
    "DLF.NS": {"name": "DLF Limited", "sector": "Real Estate", "market_cap": "Large Cap"},
    "INDUSINDBK.NS": {"name": "IndusInd Bank", "sector": "Banking", "market_cap": "Mid Cap"},
    "EICHERMOT.NS": {"name": "Eicher Motors", "sector": "Auto", "market_cap": "Mid Cap"},
    "DRREDDY.NS": {"name": "Dr. Reddy's Labs", "sector": "Pharma", "market_cap": "Large Cap"},
    "CIPLA.NS": {"name": "Cipla", "sector": "Pharma", "market_cap": "Large Cap"},
    "DIVISLAB.NS": {"name": "Divi's Laboratories", "sector": "Pharma", "market_cap": "Large Cap"},
    "APOLLOHOSP.NS": {"name": "Apollo Hospitals", "sector": "Healthcare", "market_cap": "Large Cap"},
    "PIDILITIND.NS": {"name": "Pidilite Industries", "sector": "Materials", "market_cap": "Large Cap"},
    "BRITANNIA.NS": {"name": "Britannia Industries", "sector": "FMCG", "market_cap": "Large Cap"},
    "GODREJCP.NS": {"name": "Godrej Consumer", "sector": "FMCG", "market_cap": "Large Cap"},
    "HEROMOTOCO.NS": {"name": "Hero MotoCorp", "sector": "Auto", "market_cap": "Large Cap"},
    "BAJAJ-AUTO.NS": {"name": "Bajaj Auto", "sector": "Auto", "market_cap": "Large Cap"},
    "TVSMOTOR.NS": {"name": "TVS Motor Company", "sector": "Auto", "market_cap": "Mid Cap"},
    "ASHOKLEY.NS": {"name": "Ashok Leyland", "sector": "Auto", "market_cap": "Mid Cap"},
    "YESBANK.NS": {"name": "Yes Bank", "sector": "Banking", "market_cap": "Small Cap"},
    "IDEA.NS": {"name": "Vodafone Idea", "sector": "Telecom", "market_cap": "Small Cap"},
    "SUZLON.NS": {"name": "Suzlon Energy", "sector": "Energy", "market_cap": "Small Cap"},
    "IOC.NS": {"name": "Indian Oil Corporation", "sector": "Energy", "market_cap": "Mid Cap"},
    "BPCL.NS": {"name": "Bharat Petroleum", "sector": "Energy", "market_cap": "Mid Cap"},
    "GAIL.NS": {"name": "GAIL India", "sector": "Energy", "market_cap": "Mid Cap"},
    "HINDPETRO.NS": {"name": "Hindustan Petroleum", "sector": "Energy", "market_cap": "Small Cap"},
    "TRENT.NS": {"name": "Trent Limited", "sector": "Consumer", "market_cap": "Large Cap"},
    "DMART.NS": {"name": "Avenue Supermarts", "sector": "Consumer", "market_cap": "Large Cap"},
    "BEL.NS": {"name": "Bharat Electronics", "sector": "Defense", "market_cap": "Large Cap"},
    "CHOLAFIN.NS": {"name": "Cholamandalam Inv", "sector": "Finance", "market_cap": "Large Cap"},
    
    # Global Equities & Commodities (USD)
    "AAPL": {"name": "Apple Inc.", "sector": "IT", "market_cap": "Mega Cap"},
    "MSFT": {"name": "Microsoft Corp.", "sector": "IT", "market_cap": "Mega Cap"},
    "NVDA": {"name": "NVIDIA Corp.", "sector": "IT", "market_cap": "Mega Cap"},
    "TSLA": {"name": "Tesla Inc.", "sector": "Auto", "market_cap": "Mega Cap"},
    "AMZN": {"name": "Amazon.com Inc.", "sector": "Consumer", "market_cap": "Mega Cap"},
    "GOOGL": {"name": "Alphabet Inc.", "sector": "IT", "market_cap": "Mega Cap"},
    "META": {"name": "Meta Platforms", "sector": "IT", "market_cap": "Mega Cap"},
    
    "GC=F": {"name": "Gold Futures", "sector": "Commodity", "market_cap": "Mega Cap"},
    "SI=F": {"name": "Silver Futures", "sector": "Commodity", "market_cap": "Large Cap"},
    "CL=F": {"name": "Crude Oil", "sector": "Commodity", "market_cap": "Mega Cap"},
    "BTC-USD": {"name": "Bitcoin (USD)", "sector": "Crypto", "market_cap": "Mega Cap"}
}

def get_universe_list():
    return list(NSE_UNIVERSE.keys())
